filebeat:
  image: docker.elastic.co/beats/filebeat-oss:7.12.1

  daemonset:
    filebeatConfig:
      filebeat.yml: |
        filebeat.inputs:
        - type: container
          paths:
            - /var/log/containers/*.log
          processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"
        output.elasticsearch:
          hosts: ["https://192.168.0.100:9200"]
          username: "admin"
          password: "admin"
          host: '${NODE_NAME}'
          index: "filebeat-oss-%{[agent.version]}-%{+yyyy.MM.dd}"
          ssl.verification_mode: "none"
        setup.ilm.enabled: false
        setup.template.name: "filebeat"
        setup.template.pattern: "filebeat-oss-*"
